import Head from "next/head";
import { Divider } from "@/components/Divider/Divider";
import { Footer } from "@/sections/Footer/Footer";
import { Header } from "@/sections/Header/Header";
import { IntroSection } from "@/sections/Intro/Intro";
import { TechStackSection } from "@/sections/TechStack/TechStack";
import { TimelineSection } from "@/sections/Timeline/Timeline";
import "@/style/global.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>{"Cassandra O'Connell"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>👋</text></svg>"
        />
      </Head>
      <main>
        <Header />
        <IntroSection />
        <Divider />
        <TechStackSection />
        <Divider />
        <TimelineSection timeline={{}} />
        <Footer />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  return { props: { data: {} } };
}
