import Head from "next/head";
import { Divider } from "@/components/Divider/Divider";
import { Header } from "@/sections/Header/Header";
import { Intro } from "@/sections/Intro/Intro";
import { TechStack } from "@/sections/TechStack/TechStack";
import { Timeline } from "@/sections/Timeline/Timeline";
import "@/style/global.css";
import { Footer } from "@/sections/Footer/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>{"Cassandra O'Connell"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>👋</text></svg>"
        />
      </Head>
      <main>
        <Header />
        <Intro />
        <Divider />
        <TechStack />
        <Divider />
        <Timeline />
        <Footer />
      </main>
    </>
  );
}
