import { MongoClient } from "mongodb";
import { InferGetServerSidePropsType } from "next";
import Head from "next/head";
import { Introduction } from "@/scenes/Introduction/Introduction";
import { Discovery, Experience, Timeline } from "@/types/Timeline";
import "@/style/global.css";
import { Camera } from "@/components/Camera/Camera";
import { History } from "@/scenes/History/History";
import { Skills } from "@/scenes/Skills/Skills";

export default function Home({
  data,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>{"Cassandra O'Connell"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>👋</text></svg>"
        />
      </Head>
      <Camera
        scenes={[
          <Introduction key="introduction" />,
          <History key="history" />,
          <Skills key="skills" />,
        ]}
      />
    </>
  );
}

export const getServerSideProps = async () => {
  const uri = process.env.MONGO_DB_CONNECTION_STRING;
  let timeline: Timeline | null = null;

  if (uri) {
    const client = new MongoClient(uri);

    try {
      const database = client.db("timeline");

      const discoveries = await database
        .collection<Discovery>("discoveries")
        .find({}, { sort: { start: -1 } })
        .toArray();

      const experiences = await database
        .collection<Experience>("experiences")
        .find({}, { sort: { start: -1 } })
        .toArray();

      timeline = {
        discoveries: discoveries.map(({ _id, ...discovery }) => discovery),
        experiences: experiences.map(({ _id, ...experience }) => experience),
      };
    } catch (error) {
      // TODO - log somewhere
    } finally {
      await client.close();
    }
  }

  return {
    props: {
      data: {
        timeline,
      },
    },
  };
};
